Models/Blocks/ButtonBlock.cs
using System;
using System.ComponentModel.DataAnnotations;
using EPiServer;
using EPiServer.Core;
using EPiServer.DataAbstraction;
using EPiServer.DataAnnotations;

namespace C2EpiserverBlog.Models.Blocks
{
    [ContentType(DisplayName = "ButtonBlock", GUID = "c6716618-753d-492d-8177-dec465cc7ef7", Description = "")]
    public class ButtonBlock : BlockData
    {
        [Display(Order = 1, GroupName = SystemTabNames.Content)]
        [Required]
        public virtual string ButtonText { get; set; }

        [Display(Order = 2, GroupName = SystemTabNames.Content)]
        [Required]
        public virtual Url ButtonLink { get; set; }
    }
}

Models/Other/Random.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace C2EpiserverBlog.Models.Random
{
    public class Random
    {
        public int ID { get; set; }
        public int Index { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }
}

Models/Pages/ContactPage.cs
using System;
using System.ComponentModel.DataAnnotations;
using EPiServer.Core;
using EPiServer.DataAbstraction;
using EPiServer.DataAnnotations;
using EPiServer.SpecializedProperties;

namespace C2EpiserverBlog.Models.Pages
{
    [ContentType(DisplayName = "ContactPage", GUID = "0240fd5c-306b-4db1-b46f-d7da1798cd54", Description = "")]
    public class ContactPage : PageData
    {
        [CultureSpecific]
        [Display(
                   Name = "Name",
                   Description = "Full Name",
                   GroupName = SystemTabNames.Content,
                   Order = 1)]
        public virtual string FullName { get; set; }

        [CultureSpecific]
        [Display(
           Name = "Email",
           Description = "There probably should be some validation on this",
           GroupName = SystemTabNames.Content,
           Order = 1)]
        [EmailAddress]
        public virtual string Email { get; set; }

        [CultureSpecific]
        [Display(
           Name = "Phone",
           Description = "Phone valdation",
           GroupName = SystemTabNames.Content,
           Order = 1)]
        public virtual string Phone { get; set; }
    }
}

Models/Pages/StartPage.cs
using System;
using System.ComponentModel.DataAnnotations;
using EPiServer.Core;
using EPiServer.DataAbstraction;
using EPiServer.DataAnnotations;
using EPiServer.SpecializedProperties;

namespace C2EpiserverBlog.Models.Pages
{

    [ContentType(DisplayName = "StartPage", GUID = "a6427ae7-d187-490e-8073-da57bd3e5ae6", Description = "")]
    [AvailableContentTypes(
        Availability.Specific,
        Include = new[] { typeof(TestPage), typeof(ContactPage), typeof(ThankYouPage) })]
    public class StartPage : PageData
    {
        [Display(
            GroupName = SystemTabNames.Content,
            Order = 0)]
        [CultureSpecific]
        public virtual ContentArea MainContentArea { get; set; }

        [Display(GroupName = "Concacts page")]
        public virtual PageReference ContactsPageLink { get; set; }

        [Display(GroupName = "Thankyou page")]
        public virtual PageReference ThankYouPageLink { get; set; }
    }
}

Models/Pages/TestPage.cs
using System.ComponentModel.DataAnnotations;
using C2EpiserverBlog.Models.Random;
using EPiServer.Core;
using EPiServer.DataAbstraction;
using EPiServer.DataAnnotations;

namespace C2EpiserverBlog.Models.Pages
{
    [ContentType(DisplayName = "TestPage", GUID = "6e0d0e85-517d-49ca-b2ca-55d13c40c6ad", Description = "")]
    public class TestPage : PageData
    {
        [CultureSpecific]
        [Display(
            Name = "Heading",
            Description = "This is the heading?",
            GroupName = SystemTabNames.Content,
            Order = 1)]
        public virtual string Heading { get; set; }

        [CultureSpecific]
        [Display(
            Name = "Main body",
            Description = "The main body will be shown in the main content area of the page, using the XHTML-editor you can insert for example text, images and tables.",
            GroupName = SystemTabNames.Content,
            Order = 1)]
        public virtual XhtmlString MainBody { get; set; }

        [CultureSpecific]
        [Display(
            Name = "Spell Name",
            Description = "Name of the spell found",
            GroupName = SystemTabNames.Content,
            Order = 1)]
        public virtual string SpellName { get; set; }

        [CultureSpecific]
        [Display(
            Name = "Spell description",
            Description = "Description of the spell found",
            GroupName = SystemTabNames.Content,
            Order = 1)]
        public virtual string SpellDescription { get; set; }
    }
}

Models/Pages/ThankYouPage.cs
using System;
using System.ComponentModel.DataAnnotations;
using EPiServer.Core;
using EPiServer.DataAbstraction;
using EPiServer.DataAnnotations;
using EPiServer.SpecializedProperties;

namespace C2EpiserverBlog.Models.Pages
{
    [ContentType(DisplayName = "ThankYouPage", GUID = "cd317043-f1b4-4bdd-9447-8c870a293f45", Description = "")]
    public class ThankYouPage : PageData
    {

        [CultureSpecific]
        [Display(
            Name = "Main body",
            Description = "Generic redirect after submitting contact us form",
            GroupName = SystemTabNames.Content,
            Order = 1)]
        public virtual XhtmlString MainBody { get; set; }

    }
}

Controllers/ContactPageController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using C2EpiserverBlog.Models.Pages;
using EPiServer;
using EPiServer.Core;
using EPiServer.Framework.DataAnnotations;
using EPiServer.Web.Mvc;

namespace C2EpiserverBlog.Controllers
{
    public class ContactPageController : PageController<ContactPage>
    {
        public ActionResult Index(ContactPage currentPage)
        {
            /* Implementation of action. You can create your own view model class that you pass to the view or
             * you can pass the page type for simpler templates */

            return View(currentPage);
        }
    }
}

Controllers/RandomController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace C2EpiserverBlog.Controllers
{
    public class RandomController : Controller
    {
        // GET: Random
        public ActionResult Index()
        {
            return View();
        }
    }

}

Controllers/StartPageController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using C2EpiserverBlog.Models.Pages;

using EPiServer;
using EPiServer.Core;
using EPiServer.Framework.DataAnnotations;
using EPiServer.Web.Mvc;

namespace C2EpiserverBlog.Controllers
{
    public class StartPageController : PageController<StartPage>
    {
        public ActionResult Index(StartPage currentPage)
        {
            /* Implementation of action. You can create your own view model class that you pass to the view or
             * you can pass the page type for simpler templates */

            return View(currentPage);
        }
    }
}

Controllers/TestPageController.cs
using System;
using System.Net;
using System.Web.Mvc;
using C2EpiserverBlog.Models.Pages;
using EPiServer.Web.Mvc;
using Newtonsoft.Json.Linq;

namespace C2EpiserverBlog.Controllers
{
    public class TestPageController : PageController<TestPage>
    {
        public ActionResult Index(TestPage currentPage)
        {
            return View(currentPage);
        }

        [HttpPost]
        public ActionResult Index(TestPage random, string submit)
        {
            Random rnd = new Random();
            int spellNum = rnd.Next(1, 320);
            var url = $"http://dnd5eapi.co/api/spells/{spellNum}";
            try
            {
                using (WebClient wc = new System.Net.WebClient())
                {
                    var json = wc.DownloadString(url);
                    var cleanedJson = JObject.Parse(json);

                    var something = new TestPage {  };
                    // In the real world the json.deserialzer should work, but it doesn't here. No idea why.
                    foreach (JProperty property in cleanedJson.Properties())
                    {
                        if(property.Name == "name")
                        {
                            something.SpellName = property.Value.ToString();
                        }
                        if(property.Name == "desc")
                        {
                            something.SpellDescription = property.Value.ToString();
                        }
                    }

                    return View(something);
                }
            }
            catch
            {
                throw;
            }
        }
    }
}

Views/ContactPage/Index.cshtml
@using EPiServer.Core
@using EPiServer.Web.Mvc.Html
@model C2EpiserverBlog.Models.Pages.ContactPage
<div>
    @Html.PropertyFor(m => m.Name)
    @Html.PropertyFor(m => m.Email)
    @Html.PropertyFor(m => m.Phone)
    @Html.AcceptButton()
</div>

Views/Random/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        @using (Html.BeginForm("Index", "Random", FormMethod.Post))
        {
            <input type="submit" class="" value="Random" />

            <input type="submit" class="" value="Register" />

        }

    </div>
</body>
</html>

Views/Random/Random.cshtml
@model C2EpiserverBlog.Models.Random.Random
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Random</title>
</head>
<body>
    <div> 
        @Html.LabelFor(Model => Model.ID)
        @Html.LabelFor(Model => Model.Index)
        @Html.LabelFor(Model => Model.Name)
        @Html.LabelFor(Model => Model.Description)
    </div>
</body>
</html>

Views/Shared/_Layout.cshtml
@{ 
    string AppName = "Kal's test app";
}
<!DOCTYPE html>
<html>
<head>
    <title>@AppName </title>

</head>
<body>
    <div>
        <div>
            <div>
                @Html.ActionLink(AppName, "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - @AppName</p>
        </footer>
    </div>
</body>
</html>

Views/StartPage/Index.cshtml
@using EPiServer.Core
@using EPiServer.Web.Mvc.Html

@model C2EpiserverBlog.Models.Pages.StartPage

<div>
  @Html.PropertyFor(m => m.ContactsPageLink)
  @Html.PropertyFor(m => m.ThankYouPageLink)
</div>

Views/TestPage/Index.cshtml
@using EPiServer.Core
@using EPiServer.Web.Mvc.Html
@model C2EpiserverBlog.Models.Pages.TestPage
<div>
    @Html.PropertyFor(m => m.Heading)
    @Html.PropertyFor(m => m.MainBody)
    @using (Html.BeginForm("Index", "TestPage", FormMethod.Post))
    {
        <input type="submit" class="" value="Random" />

        <input type="submit" class="" value="Register" />

    }
    @if (!string.IsNullOrEmpty(Model.SpellName))
    {
        <div>
            @Html.PropertyFor(m => m.SpellName)
        </div>
        <div>
            @Html.PropertyFor(m => m.SpellDescription)
        </div>

    }
</div>